//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VladDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientCars()
        {
            this.DTP = new HashSet<DTP>();
        }
    
        public int Id { get; set; }
        public int Model { get; set; }
        public string GosNomer { get; set; }
        public string VINNomer { get; set; }
        public int Owner { get; set; }
        public int Cost { get; set; }
        public int Sostoyanie { get; set; }
        public string Description { get; set; }
        public int OwnerCount { get; set; }
        public int Color { get; set; }
        public string Photo { get; set; }
    
        public virtual CarModels CarModels { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Sostoyanie Sostoyanie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DTP> DTP { get; set; }
    }
}
