//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VladDiplom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VDEntities : DbContext
    {
        public VDEntities()
            : base("name=VDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarModels> CarModels { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Cuzov> Cuzov { get; set; }
        public virtual DbSet<DTP> DTP { get; set; }
        public virtual DbSet<EnginePlace> EnginePlace { get; set; }
        public virtual DbSet<EngineTypes> EngineTypes { get; set; }
        public virtual DbSet<EngineVolume> EngineVolume { get; set; }
        public virtual DbSet<FuelType> FuelType { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<KPPTypes> KPPTypes { get; set; }
        public virtual DbSet<LoginData> LoginData { get; set; }
        public virtual DbSet<Marks> Marks { get; set; }
        public virtual DbSet<RulPlace> RulPlace { get; set; }
        public virtual DbSet<Sdelki> Sdelki { get; set; }
        public virtual DbSet<Sostoyanie> Sostoyanie { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechInformation> TechInformation { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<JustCars> JustCars { get; set; }
        public virtual DbSet<SdelkiView> SdelkiView { get; set; }
        public virtual DbSet<WorkersView> WorkersView { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<ClientsView> ClientsView { get; set; }
        public virtual DbSet<ClientCars> ClientCars { get; set; }
        public virtual DbSet<Engines> Engines { get; set; }
    }
}
