//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VladDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sdelki
    {
        public int Id { get; set; }
        public int Car { get; set; }
        public int Pokupatel { get; set; }
        public decimal Summa { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
