//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VladDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TechInformation()
        {
            this.CarModels = new HashSet<CarModels>();
        }
    
        public int Id { get; set; }
        public int Cuzov { get; set; }
        public int Places { get; set; }
        public int Doors { get; set; }
        public int EngPlace { get; set; }
        public int KPPType { get; set; }
        public int Engine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarModels> CarModels { get; set; }
        public virtual Cuzov Cuzov1 { get; set; }
        public virtual EnginePlace EnginePlace { get; set; }
        public virtual KPPTypes KPPTypes { get; set; }
        public virtual Engines Engines { get; set; }
    }
}
