//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VladDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkersView
    {
        public int Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Post { get; set; }
        public decimal Oklad { get; set; }
        public string Gender { get; set; }
    }
}
